databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java

Python SDK for reference: https://github.com/databricks/databricks-sdk-py/blob/main/databricks/sdk/core.py#LL392C2-L392C2.
PR Tests

Added `cluster_id` to `DatabricksConfig` for DBConnect

---

databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java.tmpl
databricks-sdk-java/src/test/resources/testdata/empty_default/.databrickscfg

Incorporate auth permutations tests from databricks/databricks-sdk-go#496.
New auth tests pass.

Synchronize auth permutation tests with Go SDK

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

Adds support for the accounts-dod.cloud.databricks.us endpoint as an accounts endpoint in the SDK.

Add accounts-dod support in the Java SDK

---

.github/workflows/release.yml

I think there are two small bugs in the configuration of the release deployment in our github action:
1. the environment variable name is incorrect: it should be OSSRH_USERNAME/OSSRH_PASSWORD instead of MAVEN_USERNAME/MAVEN_PASSWORD.
2. action-gh-release should attach these resources to the existing release that will be created by our release automation tooling. This will not be a draft release, so I'll remove that flag.

Fix release automation

---

.github/workflows/push.yml

Add merge queue for Java SDK to support merging PRs which haven't been manually updated to latest main.

Add merge queue for Java SDK

---

databricks-sdk-java/src/main/java/com/databricks/sdk/mixin/ClustersExt.java

This PR adds a retry for timing edge cases like `INVALID_STATE: Cluster XXX is in unexpected state Pending.`
Other PRs: 
- https://github.com/databricks/databricks-sdk-py/pull/283
- https://github.com/databricks/databricks-sdk-go/pull/580

Retry in `w.clusters().ensureClusterIsRunning(id)` when cluster is simultaneously started by two different processes

---

Makefile
databricks-sdk-java/src/main/java/com/databricks/sdk/core/AzureCliCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/AzureServicePrincipalCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/AzureUtils.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthManualTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java.tmpl
databricks-sdk-java/src/test/java/com/databricks/sdk/StaticEnv.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/GitHubUtils.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/TestOSUtils.java
databricks-sdk-java/src/test/resources/testdata/az

The Java SDK request authentication logic is inconsistent between the Azure login types: for service principal auth, the SDK correctly adds the X-Databricks-Azure-Workspace-Resource-Id when configured, but this is missed for Azure CLI auth. Additionally, when logging in via Azure CLI using a service principal, the service management token must also be fetched from the CLI.
This PR fixes this by defining the logic to attach these header in a common function that is used by all Azure-specific authentication types.
See https://github.com/databricks/databricks-sdk-go/pull/584 for the same change in the Go SDK.
See https://github.com/databricks/databricks-sdk-py/pull/290 for the same changes in the Python SDK.

Set necessary headers when authenticating via Azure CLI

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/GrpcTranscodingQueryParamsSerializer.java

Query parameters are determined reflectively from request classes by scanning for fields with a QueryParam annotation. Serialization of query parameters is recursive in order to support complex types like the filter structures used for listing in the SQL query history service. This PR makes the following changes:
1. Terminate recursion when the request field is an enum.
2. When iterating through the request object's fields, skip any fields not annotated with QueryParam (but recursively, all fields do need to be serialized).
3. Rename the inner class from HeaderEntry to QueryParamPair (it represents query param pairs, not header entries).
Test for this change is dependent on other testing refactors that will be merged as part of https://github.com/databricks/databricks-sdk-java/pull/139.

Fix query param serialization for requests with enums

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksError.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksException.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrorBody.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrors.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ErrorDetail.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/ApiClientTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/error/ApiErrorBodyDeserializationSuite.java

Databricks API can return error details in case of errors. In some cases, users need to access such details to be able to solve the issue. This is the case for the errors of type ErrorInfo used by the Settings Platform.
This PR adds the necessary fields to the APIError to Unmarshal the ErrorDetails and to expose the details of type ErrorInfo to the users.

Add ErrorInfo to API errors

---

LICENSE
pom.xml

We have received Ali's approval to relicense the Java SDK under the Apache License, Version 2.0.

Relicense the Java SDK using the Apache 2.0 license

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
pom.xml

* Add additional error metadata to API errors ([#153](https://github.com/databricks/databricks-sdk-java/pull/153)).
* Bugfix: Chunk streaming request bodies only ([#157](https://github.com/databricks/databricks-sdk-java/pull/157)).
* Relicense the Java SDK using the Apache 2.0 license ([#158](https://github.com/databricks/databricks-sdk-java/pull/158)).
Breaking API Changes:
* Changed `list()` method for `accountClient.metastoreAssignments()` service to return `com.databricks.sdk.service.catalog.ListAccountMetastoreAssignmentsResponse` class.
* Changed `artifactMatchers` field for `com.databricks.sdk.service.catalog.ArtifactAllowlistInfo` to `com.databricks.sdk.service.catalog.ArtifactMatcherList` class.
* Removed `owner` field for `com.databricks.sdk.service.catalog.CreateConnection`. …

Release v0.9.0

---

.codegen.json

This may happen if you retry after a codegen failure.

Don't fail codegen if the tree was already removed

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
pom.xml

* Don't fail codegen if the tree was already removed ([#164](https://github.com/databricks/databricks-sdk-java/pull/164)).
* Update OpenAPI spec to 12 Oct 2023 ([#165](https://github.com/databricks/databricks-sdk-java/pull/165)).
API Changes:
* Changed `download()` method for `accountClient.billableUsage()` service to start returning `com.databricks.sdk.service.billing.DownloadResponse` class.
* Added `com.databricks.sdk.service.billing.DownloadResponse` class.
* Changed `delete()` method for `accountClient.storageCredentials()` service with new required argument order.
* Changed `get()` method for `accountClient.storageCredentials()` service with new required argument order.
* Changed `update()` method for `accountClient.storageCredentials()` service with new required argument order.
* …

Release v0.10.0

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/Token.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/ClockSupplier.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/RealClockSupplier.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/SystemClockSupplier.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/SystemTimer.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/TokenTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/FakeClockSupplier.java

- Align with https://github.com/databricks/databricks-sdk-py/pull/392
- Add ClockSupplier so that we don't depend on system clock while testing. Modify Token class to be more test friendly. 
Unit Tests
All nightly tests passed except two tests (which failed due to Max limit of 100 scopes has been reached!). It's a known current test infra issue and unrelated to these changes.

Adjust token expiry window to 40 seconds because of Azure

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/AzureCliCredentialsProviderTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/AzureServicePrincipalCredentialsProviderTest.java

The current isAzure() logic only checks if ".azuredatabricks." is contained in the hostname, which fails for workspaces in other Azure environments. This PR copies the logic directly from the Go SDK: https://github.com/databricks/databricks-sdk-go/blob/main/config/config.go#L142

Use same logic as Go SDK for DatabricksConfig.isAzure()

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksError.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DefaultCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/NotebookNativeCredentialsProvider.java

Notebook-native authentication has been supported in the Python SDK for the last several months, and customers using the SDKs in Databricks appreciate the easier CUJ for authentication. This PR ports the behavior to the Java SDK. The approach taken for this implementation differs somewhat from the Python SDK's implementation. In particular, in Python, DBR provides some functionality to get the command context (`from dbruntime.databricks_repl_context import get_context`, `from dbruntime.sdk_credential_provider import init_runtime_native_auth`) as well as from IPython. The Java SDK uses the DBUtils object directly. However, the SDK doesn't depend on the DBUtils API (which is only in Scala), so instead we load it reflectively.
Ran in a notebook in DBR, worked.

Implement notebook-native auth for the Java SDK

---

README.md

After discussion, we decided that we're ready to mark the Java SDK at beta stability, much like the Python and Go SDKs.

Mark Java SDK as Beta

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/OAuthClient.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/ExternalBrowserCredentialsProviderTest.java

Added following utility methods to DatabricksConfig
a. setRedirectUrl: This will be passed to OAuthClient and will be used in U2M OAuth flow if client wants to provide a custom redirect Url as per OAuth configuration of their application.
b. setScopes: Clients can set custom scopes for U2M OAuth flow. If offline_access is not present, it will be added to the scopes for refresh token support.
Tested manually using JDBC driver as a client. Also, added test case for custom values of redirectUrl and scopes.

Support custom scopes and redirectUrl for U2M OAuth flow

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/AzureCliCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/CliTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigLoader.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksCliCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/Environment.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/LinuxUtilities.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/MacOSUtilities.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/OSUtilities.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/OSUtils.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/WindowsUtilities.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/ConfigResolving.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/TestOSUtils.java
databricks-sdk-java/src/test/java/com/databricks/sdk/utils/OSUtilsTest.java
examples/cli-auth-demo/pom.xml
examples/cli-auth-demo/src/main/java/com/databricks/example/CliAuthWorkspace.java

There are two problems with respect to the Java SDK's auth pathways:
1. The logic to find the `.databrickscfg` file only works on *nix, as it hard-codes the path using forward-slashes. I've rewritten this to use `Paths.get`.
2. The databricks binary on Windows is called `databricks.exe`, not `databricks`, so we need to search for the binary with OS-specific filename.
To make this change unit-testable, I introduce an `Environment` class to abstract over environment variables, the search path for the databricks CLI executable, and the operating system name. This is needed because there are both differences in the environment variable name (`PATH` in Linux/Mac vs `Path` in Windows) and in the path separator (`:` in Linux/Mac vs `;` in Windows). The only system-independent way to get the path …

Fix databricks CLI authentication on Windows

---

.codegen/api.java.tmpl
CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/AccountGroupsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/AccountServicePrincipalsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/AccountUsersAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/GroupsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/ServicePrincipalsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/iam/UsersAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/sql/ChannelName.java
pom.xml

Bug fixes:
* Fix databricks CLI authentication on Windows ([#192](https://github.com/databricks/databricks-sdk-java/pull/192)).
* Fix SCIM pagination ([#193](https://github.com/databricks/databricks-sdk-java/pull/193)).
Other changes:
* Add more detailed error message on default credentials not found error ([#180](https://github.com/databricks/databricks-sdk-java/pull/180)).
* Support custom scopes and redirectUrl for U2M OAuth flow ([#190](https://github.com/databricks/databricks-sdk-java/pull/190)).
API Changes:
* Removed `enableOptimization()` method for `workspaceClient.metastores()` service.
* Added `pipelineId` field for `com.databricks.sdk.service.catalog.TableInfo`.
* Added `enablePredictiveOptimization` field for `com.databricks.sdk.service.catalog.UpdateCatalog` and …

Release v0.13.0

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml

* Update to OpenAPI spec ([#204](https://github.com/databricks/databricks-sdk-java/pull/204)).
Note: This release contains breaking changes, please see below.
API Changes:
* [Breaking] Changed `list()` method for `workspaceClient.externalLocations()` service to require request of `com.databricks.sdk.service.catalog.ListExternalLocationsRequest` class, `workspaceClient.storageCredentials()` service to require request of `com.databricks.sdk.service.catalog.ListStorageCredentialsRequest` class and `workspaceClient.tokens()` service to return `com.databricks.sdk.service.settings.ListPublicTokensResponse` class and `com.databricks.sdk.service.catalog.ListSchemasResponse`.
* Added `nextPageToken` field for `com.databricks.sdk.service.catalog.ListExternalLocationsResponse`, …

Release v0.16.0

---

.codegen/account.java.tmpl
.codegen/workspace.java.tmpl
databricks-sdk-java/src/main/java/com/databricks/sdk/AccountClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/WorkspaceClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/sql/ChannelName.java

Feature request from @satviksr-db, allowing him to provide custom implementations of the top-level API. This mirrors what we've done in the Go SDK.
No tests needed, as this isn't a behavior change.

Allow customizing APIs in WorkspaceClient/AccountClient

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigAttribute.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigAttributeAccessor.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java

Derive config file name from attribute name
This also renames 
- `getAzureMSI` -> `getAzureMsi`
- `setAzureMSI` -> `setAzureMsi`
The old methods are kept in place but marked as deprecated.

Derive config file name from attribute name

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksCliCredentialsProvider.java

Manually tested with a profile that uses `databricks-cli` with a GCP workspace

Fix Databricks OAuth U2M on GCP

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml

* Derive config file name from attribute name ([#216](https://github.com/databricks/databricks-sdk-java/pull/216)).
* Fix Databricks OAuth U2M on GCP ([#217](https://github.com/databricks/databricks-sdk-java/pull/217)).
* Make new workspace client from account client ([#218](https://github.com/databricks/databricks-sdk-java/pull/218)).
* Skip `AccountClientIT` test in GCP / Azure ([#222](https://github.com/databricks/databricks-sdk-java/pull/222)).
* Only include request body when the OpenAPI operation indicates that there is a request body ([#223](https://github.com/databricks/databricks-sdk-java/pull/223)).
* Generate SDK ([#226](https://github.com/databricks/databricks-sdk-java/pull/226)).
API Changes:
Additions:
* Added the following fields
- Added `usePreemptibleExecutors`, `zoneId` …

Release v0.18.0

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/http/Response.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/FilesIT.java

This makes reading the header case insensitive
Ran the tests against a test environment:

Reading headers should be done in a case-insensitive manner

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/AccountClientIT.java

The current implementation of getWorkspaceClient() copies the entire config, critically reusing the cached header factory so as to use the same auth mechanism when getting a workspace client. However, at least in GCP, account-level OAuth tokens can't be used to authenticate to a workspace (probably because the audience for the account-level and workspace-level tokens is different).
This PR fixes this by copying all fields except for the auth type and header factory. Subsequent use of the config in WorkspaceClient will trigger config resolution. For GCP, this means creating a new token source using the correct host as the audience.
This ports https://github.com/databricks/databricks-sdk-go/pull/803 to the Java SDK.
Manually ran this integration test in all non-UC (Azure, AWS, GCP) and UC …

Fix getWorkspaceClient() for GCP

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/FilesIT.java

Adding integration tests for the Files API.
I'm following the same structure as for the go-sdk integration tests: https://github.com/databricks/databricks-sdk-go/blob/main/internal/files_test.go
These are the tests.

Add integration tests for the Files API

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/commons/CommonsHttpClient.java
examples/docs/src/main/java/com/databricks/example/HttpProxyExample.java

This PR sets `useSystemProperties()` when building the Commons HTTP client. This allows users to configure an HTTP proxy by setting the `https.proxyHost` and `https.proxyPort` parameters (see https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html). 
Closes #111.
Added an example. Started the HTTP proxy from https://github.com/databricks/databricks-sdk-go/pull/825, created a run configuration for the new example that sets `https.proxyHost` to `localhost` and `https.proxyPort` to `8443`, and run. I see the proxy server handling a request and the example completes successfully.

Add basic support for HTTP proxies

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml

* Added basic support for HTTP proxies ([#241](https://github.com/databricks/databricks-sdk-java/pull/241)).
* Fixed getWorkspaceClient() for GCP ([#224](https://github.com/databricks/databricks-sdk-java/pull/224)).
* Note: Backwards incompatible changes - Settings are now nested, please see the API changes below.
* Reading headers should be done in a case-insensitive manner ([#235](https://github.com/databricks/databricks-sdk-java/pull/235)).
* Added integration tests for the Files API ([#236](https://github.com/databricks/databricks-sdk-java/pull/236)).
* Supported subservices ([#237](https://github.com/databricks/databricks-sdk-java/pull/237)).
* Handled empty types in the Java SDK ([#239](https://github.com/databricks/databricks-sdk-java/pull/239)).
* Added tokei.rs lines of code …

Release v0.20.0

---

.codegen/impl.java.tmpl
databricks-sdk-java/src/main/java/com/databricks/sdk/core/http/Encoding.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/files/FilesImpl.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/http/EncodingTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/FilesIT.java

Ports https://github.com/databricks/databricks-sdk-go/pull/869 to Java SDK.
Currently, path parameters are directly interpolated into the request URL without escaping. This means that characters like `/`, `?` and `#` will not be percent-encoded and will affect the semantics of the URL, starting a new path segment, query parameters, or fragment, respectively. This means that it is impossible for users of the Files API to upload/download objects that contain `?` or `#` in their name. `/` is allowed in the path of the Files API, so it does not need to be escaped.
The Files API is currently marked with `x-databricks-multi-segment`, indicating that it should be permitted to have `/` characters but other characters need to be percent-encoded. This PR implements this.

Properly escape multi-segment path parameters

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigAttributeAccessor.java

Adjusts the field accessibility changes so they are protected behind a lock. Epic was running into this when we concurrently created WorkspaceClients and they would often read properties that another thread had re-set to unaccessible.
Synchronize on the `field` object before we mutate and read it to ensure accessibility maintains throughout the code block
No new tests. Nothing new added so existing tests should ensure logic is correct for config reading. Testing multithreaded races in this case would prove difficult.

Lock around field accessibility changes

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java

The upcoming Marketplace API introduces an API to create an analytics dashboard. This creation request is kind of a singleton, as it has no parameters. To support this, we introduce a `POST()` method with no body specified so that this resource can be created.

Support post with no body for APIs

---

.codegen.json
.codegen/error-overrides.java.tmpl
.gitattributes
README.md
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/AbstractErrorMapper.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrors.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ErrorOverride.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ErrorOverrides.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/sql/ChannelName.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/error/ErrorMapperTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/ClustersIT.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/JobsIT.java

Ports https://github.com/databricks/databricks-sdk-go/pull/864 to the Java SDK.
Most services use `RESOURCE_DOES_NOT_EXIST` error code with 404 status code to indicate that a resource doesn't exist. However, for legacy reasons, Jobs and Clusters services use `INVALID_PARAMETER_VALUE` error code with 400 status code instead. This makes tools like Terraform and UCX difficult to maintain, as these services need different error handling logic. However, we can't change these behaviors as customers already depend on the raw HTTP response status & contents.
This PR corrects these errors in the SDK itself. SDK users can then do
```java
try {
BaseJob job = w.jobs().get("123");
} catch (ResourceDoesNotExist e) {
...
}
```
just as you would expect from other resources.
Updated the README with more …

Override INVALID_PARAMETER_VALUE on fetching non-existent job/cluster

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/PrivateAccessIT.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/QueriesIT.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/VpcEndpointsIT.java

After migrating GCP to a new E2 account, several private preview APIs need to be enabled before we can run integration tests on them. This PR disables those tests until then (PrivateAccessIT, VPCEndpointsIT).
Also, I noticed that QueriesIT was very slow due to using a very small page size (2), resulting in it making 1000s of requests serially. This caused integration tests to take over 2 hours to complete. I increased this to 1000 which should cause the test to finish a bit more quickly (on the order of minutes).

Fix remaining Java integration tests

---

databricks-sdk-java/src/main/java/com/databricks/sdk/support/Paginator.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/SecretsIT.java

#266 unintentionally broke one-shot list APIs because the single page would never be fetched. This PR forces that first page to be fetched, restoring the original behavior.

Fix one shot pagination

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigAttributeAccessor.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ProxyConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/commons/CommonsHttpClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/ProxyUtils.java

Duplicate of #242. Re-created to sign commits. (This PR adds a way to provide proxy configs in the SDK directly, ability to pick up the system properties and authentication for proxy via basic or negotiate-kerberos schemes)
Documented in #242 (These changes were tested in an environment consisting of a proxy server with kerberos authentication hosted on Ubuntu and Windows VMs. The detailed testing details are documented here: https://docs.google.com/document/d/1Zxlfx-R_JytFqMZfQMBfSQ8mj4W-aHa60vw4KdjUkEc/edit)

[PECO-1542] Add a way to provide proxy details to SDK

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml

* Added retry strategy based on idempotency of requests ([#264](https://github.com/databricks/databricks-sdk-java/pull/264)).
* Fixde remaining Java integration tests ([#265](https://github.com/databricks/databricks-sdk-java/pull/265)).
* Fixed one-shot list APIs to not return null ([#266](https://github.com/databricks/databricks-sdk-java/pull/266)).
* Removed unnecessary secret from example ([#267](https://github.com/databricks/databricks-sdk-java/pull/267)).
* Fixed one shot pagination ([#268](https://github.com/databricks/databricks-sdk-java/pull/268)).
* Updated SDK to OpenAPI spec ([#269](https://github.com/databricks/databricks-sdk-java/pull/269)).
* Added a way to provide proxy details to SDK ([#271](https://github.com/databricks/databricks-sdk-java/pull/271)).
Note: This release …

Release v0.24.0

---

.codegen/api.java.tmpl
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/compute/ClustersAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/compute/CommandExecutionAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/jobs/JobsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/pipelines/PipelinesAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/provisioning/WorkspacesAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/serving/ServingEndpointsAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/sql/WarehousesAPI.java
databricks-sdk-java/src/main/java/com/databricks/sdk/service/vectorsearch/VectorSearchEndpointsAPI.java

Current implementation does not work well when client interrupts a thread where SDK code is running. Once interrupted, the logic continues to run till the timeout (default 20mins) without sleeping at all. Each time thread.sleep is called, it throws interrupt exception and this results in calling the status API continuously without delay. 
The PR is changing the handling to throw DatabricksException when the thread is interrupted so that clients can stop the processing and handle the exception as they wish.
All unit tests are successful.

Fix interrupt handling

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/ExternalBrowserCredentialsProviderTest.java

The logic for determining OIDC endpoints depends on whether a user is authenticating to the workspace or account. The Java SDK uses presence of account ID to make this decision, which is actually incorrect: logic for determining whether a client is configured at the workspace or account-level is based on the hostname. This PR fixes this logic to match the Python SDK. As a result, users are able to set the account ID configuration for Workspace clients and will still be able to authenticate with OAuth.

Fix OIDC Endpoint Fetching in DatabricksConfig for Workspace Clients

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrors.java

Fix NullPointerException when reading error response body
Fixes the following exception
```
Caused by: java.lang.NullPointerException
at java.io.Reader.<init>(Reader.java:78)
at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:921)
at org.apache.commons.io.IOUtils.toString(IOUtils.java:2681)
at com.databricks.sdk.core.error.ApiErrors.parseApiError(ApiErrors.java:70)
at com.databricks.sdk.core.error.ApiErrors.readErrorFromResponse(ApiErrors.java:34)
at com.databricks.sdk.core.error.ApiErrors.checkForRetry(ApiErrors.java:26)
...
```

Fix NullPointerException when reading error response body

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/ApiClientTest.java

Notebook native auth was not working because the API client accessed the host before the credential provider had a chance to set it. This change postpones reading the host until after the `config.authenticate()` call.
Fixes #230.
* The new API client test adds coverage for this case.
* I manually confirmed that notebook native auth now works out of the box on DBR.

Incorporate host in request after `authenticate()` call

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigLoader.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

If the configuration isn't resolved, the `env` field will be `null`, and the `toString` function would throw an NPE. This change fixes that and adds a few tests. I changed the string output to always be non-empty, even if no properties are set.
Unit tests.

Fix NPE in string function on DatabricksConfig

---

.codegen.json
README.md
shaded/.gitignore
shaded/pom.xml

A shaded JAR is necessary to run the latest version of this SDK on DBR.
Manually confirmed it is possible to build and use this JAR on DBR.

Add instructions for building a shaded JAR

---

databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

The test is written to specifically test one branch so it should be isolated from the environment. Resolve the configuration with an empty `Environment` instance to achieve this.
This test was added in #277.
* Unit test passes.
* Confirmed it also passes when environment variables that are used in the nightlies are set.

Fix test that was picking up configuration from the environment

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksEnvironment.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/commons/CommonsHttpClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/AbstractErrorMapper.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrors.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/PrivateLinkInfo.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/PrivateLinkValidationError.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/http/Response.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/ApiClientTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/AzureCliCredentialsProviderTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/FixtureServer.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/commons/CommonsHttpClientTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/error/ErrorMapperTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/AzureServicePrincipalCredentialsProviderTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/ExternalBrowserCredentialsProviderTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/mixin/ClustersExtTest.java

Port of https://github.com/databricks/databricks-sdk-go/pull/924 to the Java SDK.
When a user tries to access a Private Link-enabled workspace configured with no public internet access from a different network than the VPC endpoint belongs to, the Private Link backend redirects the user to the login page, rather than outright rejecting the request. The login page, however, is not a JSON document and cannot be parsed by the SDK, resulting in this error message:
```
$ databricks current-user me
Error: unexpected error handling request: invalid character '<' looking for beginning of value. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at …
```

Better error message when private link enabled workspaces reject requests

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/UserAgentTest.java

This PR is a port of https://github.com/databricks/databricks-sdk-go/pull/925 to the Java SDK.
Partners of Databricks need a mechanism to register themselves in libraries or applications that they write. In this way, requests made by users of those libraries will include sufficient information to link those requests to the original users.
This PR adds a new function `withPartner` that can be used by a partner to add partner information to the User-Agent header for requests made by the SDK. The new header will have the form `partner/<parther id>`. The partner identifier is opaque for the SDK, but it must be alphanumeric.
This PR also lifts the requirement that there may only be a single copy of an entry in the user agent. This allows multiple partners to register themselves in the same …

Support partners in SDK

---

pom.xml

Retry failed integration tests
Increase the retry count to 20, and replaced all tests by this test:
```
@Test
void randomlyFail(WorkspaceClient w) {
int randomNum = (int) (Math.random() * (5));
assert randomNum == 2;
}
```
Then run:
```
mvn verify
```
Results:
```
[INFO] Results:
[INFO] 
[WARNING] Flakes: 
[WARNING] com.databricks.sdk.integration.TestIT.randomlyFail(WorkspaceClient)
[ERROR]   Run 1: TestIT.randomlyFail:15
[ERROR]   Run 2:TestIT.randomlyFail:15
[ERROR]   Run 3: TestIT.randomlyFail:15
[ERROR]   Run 4: TestIT.randomlyFail:15
[ERROR]   Run 5: TestIT.randomlyFail:15
[ERROR]   Run 6: TestIT.randomlyFail:15
[INFO]   Run 7: PASS
[INFO] 
[INFO] 
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Flakes: 1
[INFO] 
[INFO] 
[INFO] --- failsafe:3.2.5:verify (default) @ …
```

Retry failed integration tests

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java

Adding `serverless_compute_id` field to the config following [the same change](https://github.com/databricks/databricks-sdk-py/pull/685) in databricks-sdk-py
Tested locally: SDK can read values from the config, getter and setter work.

Add `serverless_compute_id` field to the config

---

.codegen.json
.codegen/changelog.md.tmpl
.codegen/changelog_config.yml
.github/workflows/push.yml
test.sh

Improve Changelog by grouping changes
Recreated latest release Changelog:
```
Release v0.27.0
* Add `serverless_compute_id` field to the config ([#299](https://github.com/databricks/databricks-sdk-java/pull/299)).
* Ignore DataPlane Services during generation ([#296](https://github.com/databricks/databricks-sdk-java/pull/296)).
* Release v0.27.0 ([#301](https://github.com/databricks/databricks-sdk-java/pull/301)).
* Retry failed integration tests ([#298](https://github.com/databricks/databricks-sdk-java/pull/298)).
* Support partners in SDK ([#291](https://github.com/databricks/databricks-sdk-java/pull/291)).
* Test parsing of error messages with `int` error codes ([#303](https://github.com/databricks/databricks-sdk-java/pull/303)).
* Update OpenAPI spec …
```

[Internal] Improve Changelog by grouping changes

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/commons/CommonsHttpClient.java

This PR addresses a regression reportedly introduced in PR #290 when connecting via a proxy that requires authentication (see context).
The problem comes from a casting exception in `CommonHttpClient` which attempts to cast a `BasicHttpRequest` (which represents the next request after receiving the auth required response) into a `HttpUriRequest`. This PR solves the casting issue by processing the ancestor of both classes, `HttpRequest`. 
The regression was detected when trying to authenticate via a Proxy that requires authentication. In particular, the request to respond to the proxy's authentication request is automatically created as a `BasicHttpRequest` by the apache `HttpClient`.   
Unit tests and integration tests are passing. The fix was also verified by the user who uncovered the …

Accept any `HttpRequest` instead of `HttpUriRequest` in `CommonHttpClient`

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/AccountClientIT.java

Non-UC workspaces do not support adding SP. This is currently blocking the release pipeline due to a failing test in our integration tests. To unblock released we are only going to run this test in aws-prod-ucacct
Manually ran this test locally on ucacct and it passed
Also ran nightly over the which passed for aws-prod-acct

[Internal] Run `AccountClientIT` test only for aws-prod-ucacct

---

examples/docs/src/main/java/com/databricks/example/UnifiedAuthWorkspace.java

This PR adds an extremely simple example to show how to use workspace unified authentication. This example is meant to be used by external CI scripts that rely on examples to run integration tests.

[Internal] Add example for workspace unified authentication

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/AzureGithubOidcCredentialsProvider.java

Add missing token URL and client ID in Github OIDC Credentials Provider. 
Verified locally that these are properly passed. This change will be covered by Databricks internal integration tests.

[Fix] Add missing token URL and client ID in Github OIDC Credentials Provider

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/QueriesIT.java
databricks-sdk-java/src/test/java/com/databricks/sdk/integration/SqlIT.java

Queries return null, we need to add a check to iterate if non null. 
Note: Ideally the test should create the query history and then fetch those followed by verifying if it's the same data to properly check for E2E lifecycle.
But for just listing, the requests work (although get null response) and more tests should be added for checking create etc...
Ran Integration test locally.

[Internal] Fixed SqlIT integration tests

---

databricks-sdk-java/src/test/java/com/databricks/sdk/service/jobs/JobsImplTest.java

Adds regression tests to ensure required Jobs endpoints say pinned to API 2.1
Unit tests.

[Internal] Test that Jobs API endpoints are pinned to 2.1

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

* New DatabricksConfig() object should retain auth type as its reusing the existing authentication mechanism. This is how its done in the Py and Go SDK
* Added unit test

[Fix] DatabricksConfig: newWithWorkspaceHost should retain authType

---

databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

`getWorkspaceClient()` clears the account ID from the config, but `resolve()` may load it again if the account ID is part of the selected .databrickscfg profile or an environment variable (which it is in our integration tests).

[Internal] Fix nightly test failure

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/PrivateLinkInfo.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/error/PrivateLinkInfoTest.java

1. query returned can be null, however its not handled correctly
2. checking if query is null or not before checking for error code `private-link-validation-error`
Unit Tests

[Fix] Handle login.html incorrect validation for private link

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/AccountMetastoreAssignmentsIT.java

Currently listAccountMetastoreAssignments test assumes to have a single workspace assigned to a metastore. Updated the test to check if the expected workspace ID is present in the list of metastore assignments instead of asserting equality with the entire list.
Tested Locally

[Fix] Fix listAccountMetastoreAssignments Integration test

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ErrorDetail.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/error/ApiErrorBodyDeserializationSuite.java

Exceptions are not deserialized correctly, the message field contains the response JSON and the string 'Cannot construct instance of com.databricks.sdk.core.error.ErrorDetail, problem: Cannot invoke "Object.getClass()" because "m" is null'
In ErrorDetails class, i added a null check before the unmodifiableMap is created. 
Created an unit test in ApiErrorBodyDeserializationSuite.java
Signed-off-by: Costin Chiulan <costin.chiulan@gmail.com>

[Fix] Fix parsing issue in ErrorDetail

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml
shaded/pom.xml

* Fix listAccountMetastoreAssignments Integration test ([#350](https://github.com/databricks/databricks-sdk-java/pull/350))
* Fix parsing issue in ErrorDetail ([#328](https://github.com/databricks/databricks-sdk-java/pull/328))
* Update SDK to OpenAPI spec ([#346](https://github.com/databricks/databricks-sdk-java/pull/346)).
* Add DCO guidelines ([#351](https://github.com/databricks/databricks-sdk-java/pull/351))
* Added `workspaceClient.disableLegacyAccess()` service and `accountClient.disableLegacyFeatures()` service.
* Added `workspaceClient.temporaryTableCredentials()` service.
* Added `putAiGateway()` method for `workspaceClient.servingEndpoints()` service.
* Added `com.databricks.sdk.service.apps.ApplicationState`, `com.databricks.sdk.service.apps.ApplicationStatus`, …

[Release] Release v0.32.0

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/http/FormRequest.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/OpenIDConnectEndpoints.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/RefreshableTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/RequestBasedRetryStrategyPicker.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthLoadTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/benchmark/DatabricksAuthLoadTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/FixtureServer.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/commons/CommonsHttpClientTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/ExternalBrowserCredentialsProviderTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/retry/RequestBasedRetryStrategyPickerTest.java

This PR addresses an issue encountered during authentication, where the server returns a 429 status code when fetching OIDC endpoints from a well-known location, particularly during frequent authentication requests. The update introduces a retry mechanism within the auth flow to mitigate the impact of 429 errors.
Modified `ApiClient` object construction to allow unauthenticated calls by including authentication function injection, where within the OIDC workflow act as no-op actions. `DatabricksConfig` would now instantiate an `ApiClient` instead of a standard `CommonsHttpClient` in these cases.
errors during a complete authentication workflow, especially under high concurrent request conditions.
* Added unit tests to verify the retry functionality upon encountering a 429 response.
* …

[Fix] Retry on too many auth requests

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml
shaded/pom.xml

* Retry on too many auth requests ([#355](https://github.com/databricks/databricks-sdk-java/pull/355)).

[Release] Release v0.32.1

---

pom.xml

This PR adds another profile in `pom.xml` to allow us to skip unit tests in our nightly integration test workflow.

[Internal] Add a run-integration-tests profile that skips unit tests

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/AzureCliCredentialsProvider.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthManualTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/TestOSUtils.java

About a week ago, unit tests running on `ubuntu-latest` started failing, likely due to a new version of 22.04 being rolled out. As a result, the actual Azure CLI was getting executed instead of the stubbed version during tests. This PR fixes that by making sure the unit tests directly target the stubbed CLI.

[Fix] Fix Ubuntu unit tests on Github Actions

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/commons/CommonsHttpClient.java

Adds support to configure Retry Strategy in HttpClient. Currently only the default retry strategy is used. This strategy retries 3 times and does not have any sleep interval in between. For our use case, we would prefer using the ExponentialBackOffStrategy.
This does not affect the default behavior but gives additional options to the users.

[Feature] Experimental: Make retry strategy configurable

---

CHANGELOG.md
databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml
shaded/pom.xml

* Experimental: Make retry strategy configurable ([#363](https://github.com/databricks/databricks-sdk-java/pull/363)).
* CommonHttpsClient Builder - set timeout correctly ([#362](https://github.com/databricks/databricks-sdk-java/pull/362)).

[Release] Release v0.34.0

---

.github/workflows/external-message.yml
.github/workflows/integration-tests.yml

Old script could not be run from master due to security restrictions and there is no reliable way to detect if a user as secrets.
Run as pull_request.

[Internal] Always write message for manual test integration

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java

Adds support for cloning DatabricksConfig(), this is needed because we need a way to set configurations per API call such as 
1. timeout
2. httpClient configuration
3. debugHeaders
However, we still want to use the cached oauth token etc and we would like the header factory to be a common object across workspace clients and databricks configs
Ideally this should be supported by the SDK itself natively, however since its not supported and it will take significant migration to achieve that, this is a work around to achieve the same.  
Added UT

[Feature] DatabricksConfig: Add clone() support

---

databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigLoader.java
pom.xml

- **What** : 
- Update commons.io to fix the [CVE in the present version](https://mvnrepository.com/artifact/com.databricks/databricks-sdk-java/0.34.0). Looks like depandabot PRs are no longer being created/merged. [[Link](https://github.com/databricks/databricks-sdk-java/pull/261/files)]
- Change ini4j configuration because of vulnerability.
- **Why** 
- ini4j 0.5.4 version has an infinite loop situation in the following piece of code. This loop can cause excessive memory and CPU usage, potentially crashing the application. Alternate libraries like Apache Commons Configuration gracefully handle the situation (by limiting the recursions internally). I will raise a PR on SDK later today to replace the ini4j library. Moreover : the official site of ini4j [is up for …

[Fix] Fix vulnerabilities in the present SDK version

---

databricks-sdk-java/src/main/java/com/databricks/sdk/WorkspaceClient.java
databricks-sdk-java/src/main/java/com/databricks/sdk/mixin/JobsExt.java
databricks-sdk-java/src/test/java/com/databricks/sdk/mixin/JobsExtTest.java

Introduces extension for jobs getRun call that paginates tasks and iterations arrays in the response and returns aggregated response to the caller. This change is necessary to prepare for jobs API 2.2 release that serves paginated response. Pagination is over once the next_page_token is absent from the response. The pagination logic is not exposed to the customer.
Unit tests

[Internal] Update Jobs GetRun API to support paginated responses for jobs and ForEach tasks

---

CHANGELOG.md
databricks-sdk-java/pom.xml
examples/docs/pom.xml
examples/spring-boot-oauth-u2m-demo/pom.xml
pom.xml
shaded/pom.xml

* Update SDK to OpenAPI spec ([#389](https://github.com/databricks/databricks-sdk-java/pull/389)).
* Added `com.databricks.sdk.service.cleanrooms` package.
* Added `delete()` method for `workspaceClient.aibiDashboardEmbeddingAccessPolicy()` service.
* Added `delete()` method for `workspaceClient.aibiDashboardEmbeddingApprovedDomains()` service.
* Added `databricksGcpServiceAccount` field for `com.databricks.sdk.service.catalog.CreateCredentialRequest`.
* Added `databricksGcpServiceAccount` field for `com.databricks.sdk.service.catalog.CredentialInfo`.
* Added `gcpOptions` field for `com.databricks.sdk.service.catalog.GenerateTemporaryServiceCredentialRequest`.
* Added `databricksGcpServiceAccount` field for `com.databricks.sdk.service.catalog.UpdateCredentialRequest`.
* Added …

[Release] Release v0.37.0

---

.github/workflows/external-message.yml
.github/workflows/integration-tests.yml
.github/workflows/message.yml
.github/workflows/push.yml
.github/workflows/release.yml

Fixes #396.
Note: the YAML files were unformatted; please review with "hide whitespace".

[Internal] Migrate workflows that need write access to use hosted runners

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/UserAgentTest.java

This PR adds CI/CD environment to the User Agent of each SDK outbound request. The implementation is similar to the one used in the Go SDK. This is useful to track how often and from which CI/CD platforms our tools are being run.
Added unit tests.

[Internal] Add CICD environment to User Agent

---

databricks-sdk-java/src/main/java/com/databricks/sdk/mixin/JobsExt.java
databricks-sdk-java/src/test/java/com/databricks/sdk/mixin/JobsExtTest.java

The existing code only paginates tasks and iterations. With this PR we update the logic to also paginate job_clusters, job_parameters and repair_history. This changes are needed for [Jobs API 2.2](https://docs.databricks.com/api/workspace/jobs/getrun) compatibility.
I only ran unit test from src/test/java/com/databricks/sdk/mixin/JobsExtTest.java. I haven't tested manually

[Internal] GetRun logic paginates more arrays

---

NEXT_CHANGELOG.md
databricks-sdk-java/src/main/java/com/databricks/sdk/mixin/JobsExt.java
databricks-sdk-java/src/test/java/com/databricks/sdk/mixin/JobsExtTest.java

Introduces logic in the extension for jobs ListJobs call. The extended logic accounts for the new response format of API 2.2. API 2.1 format returns all tasks and job_cluster for each job in the jobs list. API 2.2 format truncates tasks and job_cluster to 100 elements. The extended ListJobs logic calls GetJob for each job in the list to populate the full list of tasks and job_clusters.
The code consumes iterator from `super.list` and produces iterator that contains already paginated jobs.
Unit tests. I can't do manual tests because I haven't figured out how to run the code locally.

[Internal] Update Jobs `list` function to support paginated responses

---

NEXT_CHANGELOG.md
databricks-sdk-java/src/main/java/com/databricks/sdk/mixin/JobsExt.java
databricks-sdk-java/src/test/java/com/databricks/sdk/mixin/JobsExtTest.java

Introduces logic in the extension for jobs ListRuns call. The extended logic accounts for the new response format of API 2.2. API 2.1 format returns all tasks and job_cluster for each run in the jobs list. API 2.2 format truncates tasks and job_cluster to 100 elements. The extended ListRuns logic calls GetRun for each job in the list to populate the full list of tasks and job_clusters.
The code consumes iterator from `super.listRuns` and produces iterator that contains already paginated jobs.
Unit tests. I can't do manual tests because I haven't figured out how to run the code locally.

[Internal] Update Jobs `listRuns` function to support paginated responses

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/IDToken.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/IDTokenSource.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/IDTokenTest.java

This PR adds the foundational components for OIDC support in the Databricks Java SDK:
**IDToken Class:** Encapsulates ID tokens from identity providers for OAuth flows.
**IDTokenSource** Interface: Defines a standard for retrieving ID tokens.
- Unit tests added for the IDToken class.
- IDTokenSource is not tested, as no implementation exists yet.

Add IDTokenSource Interface

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/DatabricksOAuthTokenSource.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/DatabricksOAuthTokenSourceTest.java

Merging emmyzhou-db/db-oauth-token-source into emmy-zhou/github-oidc-token-source.

Emmyzhou db/db oauth token source

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DefaultCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/GithubIDTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/TokenSourceCredentialsProvider.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthManualTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/GithubIDTokenSourceTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/TokenSourceCredentialsProviderTest.java
examples/docs/src/main/java/com/databricks/example/GithubOIDCAuthExample.java

This PR adds support for GitHub OIDC (OpenID Connect) authentication in the Databricks SDK Java.
- Added `GithubIDTokenSource` to retrieve JWT tokens from GitHub Actions environment
- Introduced new `TokenSourceCredentialsProvider` as a generic provider for token-based authentication flows
- Updated `DefaultCredentialsProvider` to support GitHub OIDC and restructured it to facilitate adding other identity providers
- Added an example demonstrating GitHub OIDC authentication with GitHub Actions
- Added unit tests for `GithubIDTokenSource` and `TokenSourceCredentialsProvider`
- Manually validated the authentication flow in a GitHub Actions workflow using the provided example

Add GitHub OIDC authentication support

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/DatabricksOAuthTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/TokenSourceCredentialsProvider.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/TokenSourceCredentialsProviderTest.java

This change extends DatabricksOAuthTokenSource from RefreshableTokenSource to enable automatic token refresh functionality while maintaining the existing OAuth token exchange flow
Unit testing

Change DatabricksOAuthTokenSource to be refreshable

---

databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DefaultCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/EnvVarIDTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/FileIDTokenSource.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/IDToken.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/EnvVarIDTokenSourceTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/FileIDTokenSourceTest.java

Add Environment Variable and File-based ID Token Sources
- Added `EnvVarIDTokenSource` to read ID tokens from environment variables
- Added `FileIDTokenSource` to read ID tokens from files
- Both implement the `IDTokenSource` interface for OIDC authentication
- Added envvar-oidc and file-oidc to the list of auth types
- Unit tests for both classes

Add support for OIDC ID token authentication using an environment variables and files

---

NEXT_CHANGELOG.md
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/RefreshableTokenSource.java

This PR introduces a new environment variable `DATABRICKS_ENABLE_EXPERIMENTAL_ASYNC_TOKEN_REFRESH` to enable asynchronous token refresh in the Databricks SDK for Java. This feature improves performance by allowing token refresh operations to happen in the background, reducing latency for API calls.
This change activates the asynchronous refresh capability that was previously added in https://github.com/databricks/databricks-sdk-java/pull/455. When enabled, stale tokens will trigger a background refresh while expired tokens will still block until a new token is fetched.
Set the environment variable:
```bash
export DATABRICKS_ENABLE_EXPERIMENTAL_ASYNC_TOKEN_REFRESH=true
```
This setting will be automatically picked up by the SDK and applied to all token refresh operations.
Manual …

Add Support for Asynchronous Token Refresh

---

databricks-sdk-java/pom.xml
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/DataPlaneTokenSource.java
pom.xml

This PR adds a dependency on [Google's AutoValue library](https://chromium.googlesource.com/external/github.com/google/auto/+/refs/tags/auto-value-1.6.2/value/userguide/index.md) to simplify the development and maintenance of value classes. See [Why should I use AutoValue?](https://chromium.googlesource.com/external/github.com/google/auto/+/refs/tags/auto-value-1.6.2/value/userguide/why.md) for more details.
The decision to use AutoValue is motivated by the fact that the Databricks SDK must support Java 8 for the foreseeable future and does not have access to new language features such as records — which would obsolete AutoValue.
Simplified one small internal class to use AutoValue and validated that the impacted unit and integration tests are fine with it.

Add a dependency on AutoValue to simplify handling of value classes.

---

.github/workflows/release.yml
pom.xml

This PR updates the release workflow to publish to the Sonatype Central Repository instead of OSSRH — which is [deprecated](https://central.sonatype.org/news/20250326_ossrh_sunset/). The PR also update the workflow to run a dry-run on pushes — which is used to validate this PR. 
See above, the workflow now does dry runs on pushes. 

Publish to the Central Repository. 

---

NEXT_CHANGELOG.md
databricks-sdk-java/src/main/java/com/databricks/sdk/core/ConfigAttributeAccessor.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/Consent.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/ExternalBrowserCredentialsProvider.java
databricks-sdk-java/src/main/java/com/databricks/sdk/core/oauth/OAuthClient.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/DatabricksConfigTest.java
databricks-sdk-java/src/test/java/com/databricks/sdk/core/oauth/ConsentTest.java

This PR adds a configurable timeout for OAuth browser authentication in the Databricks SDK for Java. 
The OAuth browser authentication flow currently waits indefinitely for user interaction, which can cause applications to hang indefinitely if users don't complete the authentication process.
The key changes include:
- New configuration option: Added `setOAuthBrowserAuthTimeout(Duration timeout)` to `DatabricksConfig` with environment variable support via `DATABRICKS_OAUTH_BROWSER_AUTH_TIMEOUT`.
- Timeout implementation: Modified the OAuth consent flow in Consent.CallbackResponseHandler to enforce the configured timeout when waiting for browser callback parameters.
- Bug fixes: Fixed ConfigAttributeAccessor to properly handle Duration, Integer, and Boolean types from environment variables. …

Add an option to set a timeout for browser confirmation in the U2M authentication flow. 

---

databricks-sdk-java/src/test/java/com/databricks/sdk/integration/EncryptionKeysIT.java

This test was disabled because the test account didn't have the right privileges to perform this action. But it does now, so I'm enabling the test again.
This is a test.

Enable Encryption Keys test
