- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/sdk-issue.md
Adds issue templates for features or bugs to the Java SDK.
> Add issue template

- .codegen.json
- .codegen/changelog.md.tmpl
- CHANGELOG.md
- Added `.codegen/changelog.md.tmpl`
- Added `version` and `toolchain` configurations to `.codegen.json`
> Integrate with auto-release toolchain

- databricks-sdk-java/src/test/java/com/databricks/sdk/integration/framework/ResourceWithCleanup.java
The order of required args to create a volume was updated in #148.
Integration tests now pass.
> Fix Files API integration test

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- pom.xml
* Implemented notebook-native auth for the Java SDK ([#171](https://github.com/databricks/databricks-sdk-java/pull/171)).
* Addeded regression question to github issue template ([#176](https://github.com/databricks/databricks-sdk-java/pull/176)).
* Marked Java SDK as Beta ([#177](https://github.com/databricks/databricks-sdk-java/pull/177)).
* Updated SDK to latest OpenAPI Spec ([#181](https://github.com/databricks/databricks-sdk-java/pull/181)).
API Changes:
* Changed `create()` method for `workspaceClient.functions()` and `workspaceClient.metastores()` service. 
* Changed the following fields:
* `inputParams` field for `com.databricks.sdk.service.catalog.CreateFunction` to `com.databricks.sdk.service.catalog.FunctionParameterInfos` class.
* `properties` field for …
> Release v0.12.0

- databricks-sdk-java/src/main/java/com/databricks/sdk/core/DefaultCredentialsProvider.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/DatabricksAuthTest.java
- Added more detailed error message for default credentials not found error - found the original error message was a bit difficult to follow / understand
- To keep consistency with the python sdk as change introduced here https://github.com/databricks/databricks-sdk-py/pull/419
> Add more detailed error message on default credentials not found error

- databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksConfig.java
Fix Azure Databricks OAuth M2M
* Manually tested with an Azure workspace
* https://github.com/databricks/eng-dev-ecosystem/actions/runs/7568909088
> Fix Azure Databricks OAuth M2M

- databricks-sdk-java/src/main/java/com/databricks/sdk/core/DefaultCredentialsProvider.java
> Tolerate missing GCP dependencies

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
Major changes:
* Allow customizing APIs in WorkspaceClient/AccountClient ([#213](https://github.com/databricks/databricks-sdk-java/pull/213)).
Bug fixes:
* Make modifications to make Azure connection work ([#202](https://github.com/databricks/databricks-sdk-java/pull/202)).
* Tolerate missing GCP dependencies ([#214](https://github.com/databricks/databricks-sdk-java/pull/214)).
> Release v0.17.1

- databricks-sdk-java/src/test/java/com/databricks/sdk/integration/AccountClientIT.java
Ref: https://github.com/databricks/databricks-sdk-go/pull/798
Nightly passed -- all tests green
> Skip `AccountClientIT` test in GCP / Azure

- README.md
[![lines of code](https://tokei.rs/b1/github/databricks/databricks-sdk-java)]([https://codecov.io/github/databricks/databricks-sdk-java](https://github.com/databricks/databricks-sdk-java))
> Added tokei.rs lines of code badge

- databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/DatabricksError.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/error/ApiErrors.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/IdempotentRequestRetryStrategy.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/NonIdempotentRequestRetryStrategy.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/RequestBasedRetryStrategyPicker.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/RetryStrategy.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/RetryStrategyPicker.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/retry/RetryUtils.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/SystemTimer.java
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/utils/Timer.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/ApiClientTest.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/DummyHttpClient.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/retry/IdempotentRequestRetryStrategyTest.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/retry/NonIdempotentRequestRetryStrategyTest.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/retry/RequestBasedRetryStrategyPickerTest.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/utils/FakeTimer.java
This is a duplicate of #249. Had to recreate because of commit signing issues.
> [PECO-1008] Add retry strategy based on idempotency of requests

- examples/docs/src/main/java/com/databricks/example/M2MAuthExample.java
A secret was committed to the repo in an example. This PR removes it. The underlying secret has been revoked so it is not usable any longer.
> Remove unnecessary secret from example

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
* Fixed interrupt handling ([#272](https://github.com/databricks/databricks-sdk-java/pull/272)).
* Added README for proxy and minor fix ([#273](https://github.com/databricks/databricks-sdk-java/pull/273)).
> Release v0.24.1

- databricks-sdk-java/src/main/java/com/databricks/sdk/core/NotebookNativeCredentialsProvider.java
Found this while working on #282.
n/a
> Add missing return

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
- shaded/pom.xml
* Fix OIDC Endpoint Fetching in DatabricksConfig for Workspace Clients ([#277](https://github.com/databricks/databricks-sdk-java/pull/277)).
* Fix NullPointerException when reading error response body ([#276](https://github.com/databricks/databricks-sdk-java/pull/276)).
* Incorporate host in request after `authenticate()` call ([#282](https://github.com/databricks/databricks-sdk-java/pull/282)).
* Fix NPE in string function on DatabricksConfig ([#285](https://github.com/databricks/databricks-sdk-java/pull/285)).
* Add instructions for building a shaded JAR ([#284](https://github.com/databricks/databricks-sdk-java/pull/284)).
* Added `ingestionDefinition` field for `com.databricks.sdk.service.pipelines.CreatePipeline`, `com.databricks.sdk.service.pipelines.EditPipeline` and …
> Release v0.25.0

- .codegen/_openapi_sha
- .codegen/account.java.tmpl
- .codegen/workspace.java.tmpl
Ignore DataPlane Services during generation until proper support is implemented
Generated SDK using local universe (which contains DataPlane services)
> Ignore DataPlane Services during generation

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
- shaded/pom.xml
* Specify proxy auth explicitly when using system proxy ([#300](https://github.com/databricks/databricks-sdk-java/pull/300)).
* Accept any `HttpRequest` instead of `HttpUriRequest` in `CommonHttpClient` ([#305](https://github.com/databricks/databricks-sdk-java/pull/305)).
* Add credential provider for Azure Github OIDC ([#307](https://github.com/databricks/databricks-sdk-java/pull/307)).
* Add Release tag and Workflow Fix ([#309](https://github.com/databricks/databricks-sdk-java/pull/309)).
* Improve Changelog by grouping changes ([#308](https://github.com/databricks/databricks-sdk-java/pull/308)).
* Test parsing of error messages with `int` error codes ([#303](https://github.com/databricks/databricks-sdk-java/pull/303)).
* Run AccountClientIT test only for aws-prod-ucacct …
> [Release] v0.27.1

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
- shaded/pom.xml
* Remove proxy settings from databricks config and use commons http client builder for connection manager ([#337](https://github.com/databricks/databricks-sdk-java/pull/337)).
* Remove Path Parameters from JSON body ([#344](https://github.com/databricks/databricks-sdk-java/pull/344)).
* Stop pagination on empty next page token ([#343](https://github.com/databricks/databricks-sdk-java/pull/343)).
> [Release] Release v0.31.1

- CHANGELOG.md
- databricks-sdk-java/pom.xml
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/UserAgent.java
- examples/docs/pom.xml
- examples/spring-boot-oauth-u2m-demo/pom.xml
- pom.xml
- shaded/pom.xml
* Make `UserAgent`'s `otherInfo` thread-safe ([#357](https://github.com/databricks/databricks-sdk-java/pull/357)).
> [Release] Release v0.32.2

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template to remove outdated check boxes and emphasize testing.
N/A
> [Internal] Refresh PR template

- NEXT_CHANGELOG.md
- databricks-sdk-java/src/main/java/com/databricks/sdk/core/ApiClient.java
- databricks-sdk-java/src/test/java/com/databricks/sdk/core/ApiClientTest.java
Fix deserialisation of empty body in HTTP responses
Added unit test. The unit test fails without this fix.
> Fix deserialisation of empty body in HTTP responses
